FROM learninglayers/tomcat
MAINTAINER Aarij Siddiqui <siddiqui ÄT dbis.rwth-aachen.de>

# Add the war from Jenkins
ADD http://layers.dbis.rwth-aachen.de/jenkins/job/Cloud-Video-Transcoder/lastSuccessfulBuild/artifact/ClViTra_2.0/target/clvitra.war /opt/tomcat/webapps/clvitra.war
