FROM shipyard/shipyard-cli
MAINTAINER Yordan Manolov <manolov@dbis.rwth-aachen.de>

#Since this Dockerfile is not based on our base image, 
# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
