DROP TABLE IF EXISTS Files;
DROP TABLE IF EXISTS Serviceflavors;
DROP TABLE IF EXISTS Services;

CREATE TABLE Services (
  ID INT(11) NOT NULL auto_increment,
  NAME CHAR(255) NOT NULL,
  TENANTID CHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  CREATIONTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT SERVICES_PK PRIMARY KEY (ID),
  CONSTRAINT SERVICES_UK1 UNIQUE KEY (NAME),
  CONSTRAINT SERVICES_UK2 UNIQUE KEY (TENANTID)
);

CREATE TABLE Serviceflavors (
  ID INT(11) NOT NULL auto_increment,
  SID INT(11) NOT NULL,
  TYPE CHAR(255) NOT NULL,
  VERSION INT(11) NOT NULL, 
  DESCRIPTION TEXT,
  CREATIONTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT SERVICEFLAVORS_PK PRIMARY KEY (ID),
  CONSTRAINT SERVICESFLAVORS_UK UNIQUE KEY (TYPE,VERSION),
  CONSTRAINT SERVICE_FK1 FOREIGN KEY (SID) REFERENCES Services(ID)
);

CREATE TABLE Files (
	ID INT(11) NOT NULL auto_increment,
	SID INT(11) NOT NULL,
	SFID INT(11) NOT NULL,
	TYPE CHAR(255) NOT NULL,
	DESCRIPTION TEXT,
	CREATIONTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FILES_PK PRIMARY KEY (ID),
	CONSTRAINT FILES_UK UNIQUE KEY (TYPE),
	CONSTRAINT SERVICE_FK2 FOREIGN KEY (SID) REFERENCES Serviceflavors(ID),
	CONSTRAINT SERVICEFLAVORS_FK1 FOREIGN KEY (SID)  REFERENCES Serviceflavors(SID),
	CONSTRAINT SERVICEFLAVORS_FK2 FOREIGN KEY (SFID) REFERENCES Serviceflavors(ID)
);